---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
        otlp:
          protocols:
            grpc:
            http:
    processors:
          batch:
    exporters:
          prometheus:
            endpoint: ":8889"
          logging:
            loglevel: debug
          file:
            path: /var/log/filename-metric.json
          file/trace:
            path: /var/log/filename-trace.json
          zipkin:
            endpoint: "http://zipkin:9411/api/v2/spans"  
    service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: [batch]
              exporters: [logging,file/trace,zipkin]
            metrics:
              receivers: [otlp]
              processors: [batch]
              exporters: [prometheus,logging,file]
