apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
  name: sample-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - env:
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_SERVICE_NAME
          value: sample-app-service
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "5000"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetrycollector:4317
        name: sample-app
        image: sample-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
