receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "localhost:8889"
  logging:
    loglevel: debug
  file:
    path: ./filename.json

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging,file]